---

language: python
python: "2.7"
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  # remove pre-installed nodejs
  - "sudo apt-get remove --purge nodejs"
  - "sudo apt-get autoremove --purge"

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local
  - node --version
  - npm --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/