---

- name: install prerequisites
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
  become: yes

- include: nodejs.yml

- include: yarn.yml
