---

- name: Install prerequisites
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - make
    - gcc
    - g++
  become: yes

- name: Download nodejs source
  get_url: url=http://mirror.oam.rocks/nodejs/v{{ nodejs_version }}/node-v{{ nodejs_version }}.tar.gz dest=/tmp/node-v{{ nodejs_version }}.tar.gz

- name: Unpack nodejs source
  unarchive: src=/tmp/node-v{{ nodejs_version }}.tar.gz dest=/tmp copy=no

- name: Configure nodejs
  shell: ./configure > /dev/null chdir=/tmp/node-v{{ nodejs_version }}

- name: Build nodejs
  shell: make -j{{ ansible_processor_cores }} > /dev/null chdir=/tmp/node-v{{ nodejs_version }}

- name: Install nodejs
  shell: make install > /dev/null chdir=/tmp/node-v{{ nodejs_version }}
  become: yes